development:
  adapter: mysql
  encoding: utf8
  database: todo
  username: root
  password:
#  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: todo_test
  username: root
  password:
#  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: todo
  username: root
  password: 
#  socket: /var/lib/mysql/mysql.sock
